travis:
  secure:
    BINSTAR_TOKEN: EbpGk6K5IOnuJtPepeQxTCgyXOrtxkDH3M77c6DJ8Yw26uqmuFAEtUGh8ajliAlwqq4pWMkYh/G62m1SdpLSv8eaCWOCxxNWpiVdw3M2vq1ep2Ojzm+YJrbg+UGSI0fUayaxCMDLC2d7bpkT5OxhhbX9oxW/5b9neufhRElr0A4VUMoLqQSbpYEMCRL4TZsC998Mp527OxjOj/9RrsldfJkr7NII5vYuNkN3rMMx4jUwn5ajKWDPWMoJVV1aF2Sx+hm/UtOM1yymKjUChrmzrmvy8YI9bzTBL6Nhw115YGdrR9pOPN2yNhNOUMJVCLlMKUunpuz8a/TH3iD29MFtossoVdARjrNgeiXXJEb4WDUJochTpiR2oN+zPNewScCMDgoPhbxFXVssdi6hszIyySwUH9/INQtomelX8xnwhKnKmny0KlrUcziO33egODFc3tx52qfpHx/fkxU4jLT0NDL6wewJ4Vk3SZJexMOKZcBHlojOVo9wPBef/UAkBSjhnT44g9Zj3JQPJ4RWz0IUcym9+9W4b/3JZXi0q9SY8HQq04uATzp7QbfqK/9sQjHob0rIE4mG39YqnhBFQ0rFYTE8zq28I3bh1f+RSuDLpBYFSB30CBE9Lx+Dkvbz5ZosI4OS3evSY00+/5TsYu5rt5xtW/GoSjtqVHUfwi6ZKtQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
