travis:
  secure:
    BINSTAR_TOKEN: RSbMGsG2ZerbwlTKwjaxeHfQE6QDYMiJd6ToHvbH3i2kX//XWUkMfmy8q0LY/ZfgPHBdI3s8d5v4OuhqlEbq8zHGD04QVyxEiENvtMZMIPnPEERZkMyn23aGHkeSI1rAk6sLPugJI0XmeFKe+iaHFA+Wk3H8u4esHyx3x9PpNtD8L/E1PrAERbFUhnXBQHaP8BTvrOnmNRHmFMrPwnf8s/rmUO8SPgbYBhFviA9Kzx4sH7c/HCa1Rr7nPK84iVRdr2ZJksiHo//tyjsoo+s/ELzYvReOmU7FetVDyp2YE4b/3vitlVOEM/LMLIkTEWfNXN1qkTNUr4Aa360+tbpZy/N6PCXROprzKbA6VVjiXbo3I/qqAxzFUYBQ8yIF3FUWSdBBR6gNrUEGDlAqP4wq9seVPlFoG8N9HcGS2C25WVM7qe6KaQSPlOiy3/s465jPWnfSIsWkAy/cYIul794Ce2yvMM4Tz5pkCf9CyUFE57MxUfNVN21G+m2cX7Tcp5c2o9C+7lx+3hc/0dQQu0gvbAiPYci3cxQYrTpAJDF6ZLwF2wZRLDYhFFzO6Vps/z8RtlXb1J/Vmp9Iuyn6WzMQJ6hVewbZhvJPR3ZQwL2DdOt1ZOZBhjS6My1T84UYjXaIKezgCTqWF21j5yc9hWWa7mftv++/XDgt/tyEaSvNwpI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
