travis:
  secure:
    BINSTAR_TOKEN: bJTjbWIMgUgAffVPpPwUGBxvtWetD/FEfs0klnrXUugLIHmSZ3enmbwm0UWU/nZ5U0Czbixp/6w4Iss5utgVB82x9NQThLT3vx9Y7i8frIMJPC6ZvV1pO3MgXjuGAWtzjXlG10Oq/4cQJPlObNYlgAGgpRikww74qVYNTu9873oNUZ7nbxlwfMJcwecXVXYB5bNDIx61KdWb78JbytrzHKRn6PdWt+CDA6TGtFBkXQXcJiNOTfT26OE9i1NO0XxiF3PT6A+1Ep+wt+eWtYYqdw3yysCuh7ff3yQmI0Mev6zJpXsxaK7ISy0zzpFJGTpgjiGglSjLJSoYpjNLbfT2TzRX4y6UNvj/taLy9kp5NkfLqJNBEItLASaMgAQnUyMXFckAlz+iD0MMN8uP4LPoYjUs587xXeilkMEeH3kT/AJxilLXh1ANDrNd2BjzRSFAOBJqe7E1/OfkC9S5Ww9TZnsJE4kuifER8Dbc0VdV03pBKYLU0hBpMkGMucDrnO/zI3tZMsRP1//UAQOqM0CAdScZLKL6BoKhFFACfyUXBgVffnlf/7ogQFH4c6TixexnPHd5xsGnoPxtwcm7OlbD9+TBjHpYEQRtYN69FHkOLmONCOgbCwAKMD/dVtFXNYqScjVajSQMqpvK0Rvl+83rBotaM3WT8/fJUUipwQTYLOA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
